changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: CI / Infrastructure
      labels:
        - github-actions
        - ci
    - title: Other Changes
      labels:
        - "*"
